import os
from pathlib import Path

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, LogInfo, OpaqueFunction
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def _truthy(value):
    return value.lower() in ("1", "true", "yes", "on")


def _find_workspace_rviz(package_share_directory):
    for parent in Path(package_share_directory).parents:
        candidate = parent / "bringup" / "rviz" / "robocup_navigation.rviz"
        if candidate.is_file():
            return str(candidate)
    return ""


def _launch_rviz(context, *args, **kwargs):
    if not _truthy(LaunchConfiguration("rviz").perform(context)):
        return []

    package_share_directory = kwargs["package_share_directory"]
    explicit_config = LaunchConfiguration("rviz_config").perform(context)
    config_name = LaunchConfiguration("config").perform(context)
    legacy_map_name = LaunchConfiguration("map").perform(context)
    if legacy_map_name:
        config_name = legacy_map_name

    if explicit_config:
        rviz_config_file = explicit_config
    else:
        map_config = os.path.join(package_share_directory, "rviz", f"{config_name}.rviz")
        if os.path.isfile(map_config):
            rviz_config_file = map_config
        else:
            rviz_config_file = _find_workspace_rviz(package_share_directory)
        if not rviz_config_file:
            packaged_rviz = sorted((Path(package_share_directory) / "rviz").glob("*.rviz"))
            rviz_config_file = str(packaged_rviz[0]) if packaged_rviz else ""

    return [
        LogInfo(msg=["Using RViz config: ", rviz_config_file]),
        Node(package="rviz2",
             executable="rviz2",
             name="rvizualizer",
             arguments=["-d", rviz_config_file],
             output="screen"),
    ]


def _launch_trg_node(context, *args, **kwargs):
    package_share_directory = kwargs["package_share_directory"]
    params_file = os.path.join(package_share_directory,
                               "config",
                               LaunchConfiguration("params").perform(context))
    config_name = LaunchConfiguration("config").perform(context)
    legacy_map_name = LaunchConfiguration("map").perform(context)
    if legacy_map_name:
        config_name = legacy_map_name
    map_config_path = LaunchConfiguration("map_config_path").perform(context)
    if not map_config_path:
        map_config_path = os.path.join(package_share_directory, "config", f"{config_name}.yaml")

    return [
        Node(package='trg_planner_ros',
             executable='trg_ros2_node',
             name='trg_ros2_node',
             parameters=[
                 params_file, {
                     'mapConfig': config_name,
                     'mapConfigPath': map_config_path,
                     'prebuiltMapPath': LaunchConfiguration('map_path'),
                     'boundaryFile': LaunchConfiguration('boundary_file'),
                     'boundaryKeepoutMargin': LaunchConfiguration('boundary_keepout_margin'),
                 }
             ],
             output='screen')
    ]


def generate_launch_description():
    # Declare launch arguments
    rviz_arg = DeclareLaunchArgument('rviz',
                                     default_value='false',
                                     description='Whether to launch RViz')
    config_arg = DeclareLaunchArgument(
        'config',
        default_value='robocup_default',
        description='Scene-independent TRG hyperparameter YAML stem in TRG-planner/config')
    legacy_map_arg = DeclareLaunchArgument(
        'map',
        default_value='',
        description='Deprecated alias for config. Do not use for scene-specific YAMLs.')
    map_config_path_arg = DeclareLaunchArgument(
        'map_config_path',
        default_value='',
        description='Explicit full TRG YAML path. Usually generated by bringup scripts.')
    map_path_arg = DeclareLaunchArgument(
        'map_path',
        default_value='',
        description='Prebuilt prior-map PCD path injected into the generic TRG config.')
    boundary_file_arg = DeclareLaunchArgument(
        'boundary_file',
        default_value='',
        description='Allowed-area boundary YAML. Enables TRG boundary filtering when set.')
    boundary_keepout_margin_arg = DeclareLaunchArgument(
        'boundary_keepout_margin',
        default_value='',
        description='Optional boundary keepout margin override in meters. Empty keeps YAML value.')
    params_arg = DeclareLaunchArgument(
        'params',
        default_value='robocup_params.yaml',
        description='ROS parameter YAML file in the package config directory')
    rviz_config_arg = DeclareLaunchArgument(
        'rviz_config',
        default_value='',
        description='Explicit RViz config file. Defaults to map RViz, then RoboCup workspace RViz.')
    pose_bridge_arg = DeclareLaunchArgument(
        'pose_bridge',
        default_value='true',
        description='Bridge RViz /initialpose to the TRG odometry input for TRG-only debugging.')
    pose_frame_arg = DeclareLaunchArgument(
        'pose_frame',
        default_value='map',
        description='Frame id used by the RViz initial-pose odometry bridge.')
    odom_topic_arg = DeclareLaunchArgument(
        'odom_topic',
        default_value='/laser_odometry',
        description='Odometry topic published by the RViz initial-pose bridge.')

    # Get the path to the configuration files
    package_share_directory = get_package_share_directory('trg_planner_ros')

    pose_bridge_node = Node(
        package='trg_planner_ros',
        executable='fake_pose_pub.py',
        name='trg_rviz_pose_bridge',
        condition=IfCondition(LaunchConfiguration('pose_bridge')),
        parameters=[{
            'frame_id': LaunchConfiguration('pose_frame'),
            'odom_topic': LaunchConfiguration('odom_topic'),
            'initialpose_topic': '/initialpose',
            'goal_in_topic': '',
            'goal_out_topic': '',
        }],
        output='screen')

    return LaunchDescription([
        rviz_arg,
        config_arg,
        legacy_map_arg,
        map_config_path_arg,
        map_path_arg,
        boundary_file_arg,
        boundary_keepout_margin_arg,
        params_arg,
        rviz_config_arg,
        pose_bridge_arg,
        pose_frame_arg,
        odom_topic_arg,
        OpaqueFunction(function=_launch_trg_node,
                       kwargs={'package_share_directory': package_share_directory}),
        pose_bridge_node,
        OpaqueFunction(function=_launch_rviz,
                       kwargs={'package_share_directory': package_share_directory}),
    ])
