isVerbose: false
timer:
  graphRate: 5.0
  planningRate: 10.0
map:
  isPrebuiltMap: true
  prebuiltMapPath: "/home/bichy/robocup_ws/SuperOdom/map_by_scanner/k-rail.pcd"
  waitPoseBeforeInit: true
  isVoxelize: true
  voxelSize: 0.02
trg:
  isPrebuiltTRG: false
  prebuiltTRGPath: ""
  isUpdate: false
  expandDist: 0.65
  robotSize: 0.5
  sampleNum: 20
  randomSeed: 7
  deterministicSampling: true
  heightThreshold: 0.4
  collisionThreshold: 0.1
  updateCollisionThreshold: 0.5
  safetyFactor: 3.0
  goalTolerance: 0.3
boundary:
  enabled: false
  allowedAreaPath: ""
  keepoutMargin: 0.0
